# Generated by Django 5.2.15 on 2026-06-09 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('PROCESSED', 'Processed')], default='OPEN', max_length=32)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HarJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('LIVE_BATCH', 'Live batch'), ('FINAL_TRIP', 'Final trip')], max_length=32)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('STARTED', 'Started'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure')], default='PENDING', max_length=32)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='har_jobs', to='mobility.trip')),
            ],
        ),
        migrations.CreateModel(
            name='SensorWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_timestamp', models.DateTimeField()),
                ('end_timestamp', models.DateTimeField()),
                ('sample_count', models.PositiveIntegerField()),
                ('frequency_hz', models.PositiveIntegerField()),
                ('matrix', models.JSONField(blank=True, null=True)),
                ('object_key', models.CharField(blank=True, max_length=512)),
                ('is_synced', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_windows', to='mobility.trip')),
            ],
            options={
                'indexes': [models.Index(fields=['trip', 'start_timestamp'], name='mobility_se_trip_id_e05376_idx')],
                'constraints': [models.UniqueConstraint(fields=('trip', 'start_timestamp', 'end_timestamp'), name='unique_sensor_window_per_trip_time_range')],
            },
        ),
        migrations.CreateModel(
            name='GpsPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('speed_mps', models.FloatField(default=0)),
                ('accuracy_meters', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_points', to='mobility.trip')),
            ],
            options={
                'indexes': [models.Index(fields=['trip', 'timestamp'], name='mobility_gp_trip_id_f00ff8_idx')],
            },
        ),
    ]
