# Generated by Codex on 2026-06-09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mobility", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trips",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
