# Generated by Django 5.2.15 on 2026-06-12 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobility', '0004_diary_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TripIngestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_session_id', models.CharField(max_length=64)),
                ('device_id', models.CharField(blank=True, max_length=128)),
                ('schema_version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('RECEIVING', 'Receiving'), ('READY_TO_PROCESS', 'Ready to process'), ('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('PROCESSED', 'Processed'), ('COMPLETED', 'Completed'), ('FAILED_RETRYABLE', 'Failed (retryable)'), ('FAILED_FINAL', 'Failed (final)')], default='CREATED', max_length=32)),
                ('expected_parts', models.JSONField(default=dict)),
                ('raw_base_path', models.CharField(blank=True, max_length=512)),
                ('manifest_sha256', models.CharField(blank=True, max_length=64)),
                ('total_size_bytes', models.BigIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('timezone', models.CharField(blank=True, max_length=64)),
                ('app_version', models.CharField(blank=True, max_length=32)),
                ('device_platform', models.CharField(blank=True, max_length=32)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('queued_at', models.DateTimeField(blank=True, null=True)),
                ('started_processing_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingestions', to='mobility.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_ingestions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TripIngestionPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('gps_points', 'GPS points'), ('state_transitions', 'State transitions'), ('sensor_windows', 'Sensor windows')], max_length=32)),
                ('sequence', models.PositiveIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('object_key', models.CharField(max_length=512)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ingestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='mobility.tripingestion')),
            ],
        ),
        migrations.AddIndex(
            model_name='tripingestion',
            index=models.Index(fields=['user', 'status'], name='mobility_tr_user_id_7fcf9f_idx'),
        ),
        migrations.AddConstraint(
            model_name='tripingestion',
            constraint=models.UniqueConstraint(fields=('user', 'client_session_id'), name='unique_ingestion_per_user_session'),
        ),
        migrations.AddConstraint(
            model_name='tripingestionpart',
            constraint=models.UniqueConstraint(fields=('ingestion', 'kind', 'sequence'), name='unique_part_per_ingestion_kind_sequence'),
        ),
    ]
