# Generated by Django 5.2.15 on 2026-06-20 17:23

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobility', '0006_split_tripingestion_phase_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='distance_meters',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='path',
            field=django.contrib.gis.db.models.fields.LineStringField(blank=True, geography=True, null=True, spatial_index=False, srid=4326),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=django.contrib.postgres.indexes.GistIndex(fields=['path'], name='mobility_tr_path_12b0ca_gist'),
        ),
    ]
