# Generated by Django 5.2.15 on 2026-06-27 15:00

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobility', '0009_mobilitysegment_path'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HabitualPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('radius_meters', models.FloatField(default=0)),
                ('state', models.CharField(choices=[('CANDIDATE', 'Candidate'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected')], default='CANDIDATE', max_length=16)),
                ('visit_count', models.PositiveIntegerField(default=0)),
                ('distinct_days', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(blank=True, choices=[('casa', 'Casa'), ('universita', 'Universita'), ('lavoro', 'Lavoro'), ('palestra', 'Palestra'), ('altro', 'Altro')], max_length=16)),
                ('custom_name', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habitual_places', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'state'], name='mobility_ha_user_id_c2e7d0_idx')],
            },
        ),
    ]
