# Generated by Django 5.2.15 on 2026-06-27 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobility', '0011_candidatevisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatevisit',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='mobility.habitualplace'),
        ),
    ]
