# Generated by Django 5.2.15 on 2026-06-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobility', '0012_candidatevisit_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitualplace',
            name='manually_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
