# Generated by Django 5.2.15 on 2026-06-27 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobility', '0013_habitualplace_manually_reviewed'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualStopInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_timestamp', models.DateTimeField()),
                ('end_timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_stop_intervals', to='mobility.trip')),
            ],
            options={
                'ordering': ['start_timestamp'],
                'indexes': [models.Index(fields=['trip', 'start_timestamp'], name='mobility_vstop_trip_id_idx')],
                'constraints': [models.UniqueConstraint(fields=('trip', 'start_timestamp', 'end_timestamp'), name='unique_virtual_stop_interval_per_trip_time_range')],
            },
        ),
    ]
