# Generated by Django 5.2.15 on 2026-06-27 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobility', '0014_virtualstopinterval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobilitysegment',
            name='place',
        ),
        migrations.DeleteModel(
            name='SignificantPlace',
        ),
    ]
