# Generated by Django 5.2.15 on 2026-06-29 13:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobility', '0016_placeminingstatus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tripingestion',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tripingestion',
            name='recording_abandoned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tripingestion',
            name='recording_closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tripingestion',
            name='recording_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='tripingestion',
            index=models.Index(fields=['user', 'recording_started_at'], name='mobility_tr_user_id_13e7c3_idx'),
        ),
        migrations.AddConstraint(
            model_name='tripingestion',
            constraint=models.UniqueConstraint(condition=models.Q(('recording_abandoned_at__isnull', True), ('recording_closed_at__isnull', True), ('recording_started_at__isnull', False)), fields=('user',), name='unique_active_ingestion_per_user'),
        ),
    ]
