# Generated by Django 5.2.15 on 2026-06-30 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobility', '0019_trip_reloaded_from_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripingestion',
            name='source_trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replay_ingestions', to='mobility.trip'),
        ),
    ]
