# Generated by Django 5.2.15 on 2026-06-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobility', '0020_tripingestion_source_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
