# Generated by Django 5.2.15 on 2026-07-11 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobility', '0022_trip_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripingestion',
            name='app_version',
        ),
        migrations.RemoveField(
            model_name='tripingestion',
            name='device_platform',
        ),
        migrations.RemoveField(
            model_name='tripingestion',
            name='schema_version',
        ),
        migrations.RemoveField(
            model_name='tripingestion',
            name='timezone',
        ),
    ]
