# Generated by Django 5.2.15 on 2026-07-12 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobility', '0027_remove_harjob_kind'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripingestion',
            name='manifest_sha256',
        ),
    ]
