# Generated by Django 5.2.15 on 2026-07-12 16:02
#
# Converte mobility_rawsensorreading in hypertable TimescaleDB (ADR 0001).
# L'estensione viene creata dal provisioning del database (initdb script),
# come gia' avviene per PostGIS: qui la migration si limita a chiamare
# create_hypertable se l'estensione risulta installata, altrimenti la tabella
# resta una tabella PostgreSQL normale (stesso pattern di fallback del DBSCAN).

import django.db.models.deletion
from django.db import migrations, models

_CREATE_HYPERTABLE_SQL = """
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'timescaledb') THEN
        PERFORM public.create_hypertable(
            'mobility_rawsensorreading',
            'timestamp',
            chunk_time_interval => INTERVAL '1 day',
            if_not_exists => TRUE,
            migrate_data => TRUE
        );
    ELSE
        RAISE NOTICE
            'timescaledb non installata: mobility_rawsensorreading resta una tabella normale';
    END IF;
END
$$;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('mobility', '0028_remove_tripingestion_manifest_sha256'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawSensorReading',
            fields=[
                ('pk', models.CompositePrimaryKey('trip_id', 'timestamp', blank=True, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('accel_x', models.FloatField()),
                ('accel_y', models.FloatField()),
                ('accel_z', models.FloatField()),
                ('gyro_x', models.FloatField()),
                ('gyro_y', models.FloatField()),
                ('gyro_z', models.FloatField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_sensor_readings', to='mobility.trip')),
            ],
        ),
        migrations.RunSQL(
            sql=_CREATE_HYPERTABLE_SQL,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
