# Generated by Django 5.2.15 on 2026-09-01 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobility', '0030_enable_timescale_for_rawsensorreading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripingestionpart',
            name='size_bytes',
        ),
    ]
