# Generated by Django 5.2.15 on 2026-09-03 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobility', '0032_rename_ingestion_to_upload'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tripupload',
            new_name='mobility_tr_user_id_683856_idx',
            old_name='mobility_tr_user_id_013802_idx',
        ),
        migrations.RenameIndex(
            model_name='tripupload',
            new_name='mobility_tr_user_id_467800_idx',
            old_name='mobility_tr_user_id_4b7a85_idx',
        ),
        migrations.RenameIndex(
            model_name='tripupload',
            new_name='mobility_tr_user_id_54eab0_idx',
            old_name='mobility_tr_user_id_13e7c3_idx',
        ),
        migrations.AlterField(
            model_name='tripupload',
            name='source_trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replay_uploads', to='mobility.trip'),
        ),
        migrations.AlterField(
            model_name='tripupload',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploads', to='mobility.trip'),
        ),
        migrations.AlterField(
            model_name='tripupload',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_uploads', to=settings.AUTH_USER_MODEL),
        ),
    ]
