# Generated by Django 5.2.15 on 2026-09-04 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobility', '0033_rename_mobility_tr_user_id_013802_idx_mobility_tr_user_id_683856_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statetransition',
            name='reason',
        ),
    ]
