# Generated by Django 5.2.15 on 2026-09-04 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobility', '0034_remove_statetransition_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripupload',
            name='core_payload_size_bytes',
        ),
        migrations.RemoveField(
            model_name='tripupload',
            name='total_size_bytes',
        ),
    ]
