# Generated by Django 5.2.15 on 2026-09-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobility', '0035_remove_tripupload_core_payload_size_bytes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpspoint',
            name='speed_mps',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
