# Generated by Django 5.2.15 on 2026-06-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprivacysettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprivacysettings',
            name='is_first_login',
            field=models.BooleanField(default=True),
        ),
    ]
